---@meta

---@class VaultSpell
---@field profile string
---@field commID CommID
---@field description string
---@field cooldown number
---@field fullName string
---@field icon integer?
---@field castbar (0 | 1 | 2)?
---@field actions VaultSpellAction[]
---@field author string
---@field items table
---@field conditions ConditionDataTable
